/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context as Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  UserWhereUniqueInput: { // input type
    id: number; // Int!
  }
  createAddressInput: { // input type
    city: string; // String!
    country: string; // String!
    houseNumber: string; // String!
    postalCode: string; // String!
    street: string; // String!
    telephone: string; // String!
    userId: number; // Int!
  }
  createCategoryInput: { // input type
    name: string; // String!
  }
  createOrderInput: { // input type
    addressId: number; // Int!
    orderStatus: NexusGenEnums['OrderStatus']; // OrderStatus!
    totalPrice: number; // Float!
    userId: number; // Int!
  }
  createOrderItemInput: { // input type
    orderId?: number | null; // Int
    productId?: number | null; // Int
    quantity?: number | null; // Int
  }
  createProductInput: { // input type
    categoryId: number; // Int!
    description: string; // String!
    discountId?: number | null; // Int
    image: string; // String!
    name: string; // String!
    price: number; // Float!
  }
  createUserInput: { // input type
    email: string; // String!
    firstName: string; // String!
    lastName: string; // String!
    password: string; // String!
    phone: string; // String!
  }
  getOrderInput: { // input type
    id: number; // Int!
  }
  getOrderItemsIdInput: { // input type
    orderId: number; // Int!
  }
  getProductInput: { // input type
    id: number; // Int!
  }
}

export interface NexusGenEnums {
  OrderStatus: "CANCELED" | "COMPLETED" | "ONGOING"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Address: { // root type
    city: string; // String!
    country: string; // String!
    houseNumber: string; // String!
    id: number; // Int!
    postalCode: string; // String!
    street: string; // String!
    telephone: string; // String!
    userId: number; // Int!
  }
  Category: { // root type
    createdAt: string; // String!
    id: number; // Int!
    name: string; // String!
    updatedAt: string; // String!
  }
  Mutation: {};
  Order: { // root type
    addressId: number; // Int!
    createdAt: string; // String!
    id: number; // Int!
    orderStatus: NexusGenEnums['OrderStatus']; // OrderStatus!
    totalPrice: number; // Float!
    updatedAt: string; // String!
    userId: number; // Int!
  }
  Product: { // root type
    categoryId: number; // Int!
    createdAt: string; // String!
    description: string; // String!
    discountId?: number | null; // Int
    id: number; // Int!
    image: string; // String!
    name: string; // String!
    price: number; // Float!
    updatedAt: string; // String!
  }
  Query: {};
  User: { // root type
    balance: number; // Float!
    createdAt: string; // String!
    email: string; // String!
    firstName: string; // String!
    id: number; // Int!
    lastName: string; // String!
    password: string; // String!
    phone: string; // String!
    updatedAt: string; // String!
  }
  orderItem: { // root type
    createdAt: string; // String!
    id: number; // Int!
    orderId: number; // Int!
    productId: number; // Int!
    quantity: number; // Int!
    updatedAt: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Address: { // field return type
    city: string; // String!
    country: string; // String!
    houseNumber: string; // String!
    id: number; // Int!
    postalCode: string; // String!
    street: string; // String!
    telephone: string; // String!
    userId: number; // Int!
  }
  Category: { // field return type
    createdAt: string; // String!
    id: number; // Int!
    name: string; // String!
    updatedAt: string; // String!
  }
  Mutation: { // field return type
    createAddress: NexusGenRootTypes['Address']; // Address!
    createCategory: NexusGenRootTypes['Category']; // Category!
    createOrder: NexusGenRootTypes['Order']; // Order!
    createOrderItem: NexusGenRootTypes['orderItem']; // orderItem!
    createProduct: NexusGenRootTypes['Product']; // Product!
    register: NexusGenRootTypes['User']; // User!
  }
  Order: { // field return type
    addressId: number; // Int!
    createdAt: string; // String!
    id: number; // Int!
    orderStatus: NexusGenEnums['OrderStatus']; // OrderStatus!
    totalPrice: number; // Float!
    updatedAt: string; // String!
    userId: number; // Int!
  }
  Product: { // field return type
    categoryId: number; // Int!
    createdAt: string; // String!
    description: string; // String!
    discountId: number | null; // Int
    id: number; // Int!
    image: string; // String!
    name: string; // String!
    price: number; // Float!
    updatedAt: string; // String!
  }
  Query: { // field return type
    getOrder: NexusGenRootTypes['Order']; // Order!
    getOrderItems: NexusGenRootTypes['orderItem'][]; // [orderItem!]!
    getProduct: NexusGenRootTypes['Product']; // Product!
    user: NexusGenRootTypes['User']; // User!
  }
  User: { // field return type
    balance: number; // Float!
    createdAt: string; // String!
    email: string; // String!
    firstName: string; // String!
    id: number; // Int!
    lastName: string; // String!
    password: string; // String!
    phone: string; // String!
    updatedAt: string; // String!
  }
  orderItem: { // field return type
    createdAt: string; // String!
    id: number; // Int!
    orderId: number; // Int!
    productId: number; // Int!
    quantity: number; // Int!
    updatedAt: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Address: { // field return type name
    city: 'String'
    country: 'String'
    houseNumber: 'String'
    id: 'Int'
    postalCode: 'String'
    street: 'String'
    telephone: 'String'
    userId: 'Int'
  }
  Category: { // field return type name
    createdAt: 'String'
    id: 'Int'
    name: 'String'
    updatedAt: 'String'
  }
  Mutation: { // field return type name
    createAddress: 'Address'
    createCategory: 'Category'
    createOrder: 'Order'
    createOrderItem: 'orderItem'
    createProduct: 'Product'
    register: 'User'
  }
  Order: { // field return type name
    addressId: 'Int'
    createdAt: 'String'
    id: 'Int'
    orderStatus: 'OrderStatus'
    totalPrice: 'Float'
    updatedAt: 'String'
    userId: 'Int'
  }
  Product: { // field return type name
    categoryId: 'Int'
    createdAt: 'String'
    description: 'String'
    discountId: 'Int'
    id: 'Int'
    image: 'String'
    name: 'String'
    price: 'Float'
    updatedAt: 'String'
  }
  Query: { // field return type name
    getOrder: 'Order'
    getOrderItems: 'orderItem'
    getProduct: 'Product'
    user: 'User'
  }
  User: { // field return type name
    balance: 'Float'
    createdAt: 'String'
    email: 'String'
    firstName: 'String'
    id: 'Int'
    lastName: 'String'
    password: 'String'
    phone: 'String'
    updatedAt: 'String'
  }
  orderItem: { // field return type name
    createdAt: 'String'
    id: 'Int'
    orderId: 'Int'
    productId: 'Int'
    quantity: 'Int'
    updatedAt: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createAddress: { // args
      input: NexusGenInputs['createAddressInput']; // createAddressInput!
    }
    createCategory: { // args
      input: NexusGenInputs['createCategoryInput']; // createCategoryInput!
    }
    createOrder: { // args
      input: NexusGenInputs['createOrderInput']; // createOrderInput!
    }
    createOrderItem: { // args
      input: NexusGenInputs['createOrderItemInput']; // createOrderItemInput!
    }
    createProduct: { // args
      input: NexusGenInputs['createProductInput']; // createProductInput!
    }
    register: { // args
      input: NexusGenInputs['createUserInput']; // createUserInput!
    }
  }
  Query: {
    getOrder: { // args
      where: NexusGenInputs['getOrderInput']; // getOrderInput!
    }
    getOrderItems: { // args
      where: NexusGenInputs['getOrderItemsIdInput']; // getOrderItemsIdInput!
    }
    getProduct: { // args
      where: NexusGenInputs['getProductInput']; // getProductInput!
    }
    user: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}